### ISSUE TITLE
Carriage return error on OSX Yosemite

### ISSUE THREAD

**Issue by bencooling** [gevorg/htpasswd#4]
Installed through npm on OSX Yosemite. 
When I type htpasswd command, I get an error regarding a carriage return?

    htpasswd
    > env: node\r: No such file or directory

**Comment by gevorg** [comment]
Thank You, please recheck.

**Comment by bencooling** [comment]
Great thanks a lot :-)

**Comment by dharapvj** [comment]
Hello, I am getting the same error on Ubuntu.

````
$ htpasswd users.htpasswd devuser
/usr/bin/env: ‘node\r’: No such file or directory
````

Environment Details:
````
cmsuser@CMS-REST-Provider:~/cms/data$ node -v
v6.2.2
cmsuser@CMS-REST-Provider:~/cms/data$ npm -v
3.9.5
````

I connect to ubuntu machine via Putty on windows.. (if that matters)

**Comment by gevorg** [comment]
@dharapvj thanks for reporting, fixed and published to npm.
